# Generated by Django 3.1.6 on 2021-03-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210323_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_description',
            name='empid',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task_description',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task_description',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='task_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='task_type',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
