# Generated by Django 3.1.6 on 2021-03-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210326_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local_report',
            name='rtype',
            field=models.CharField(max_length=1001),
        ),
        migrations.AlterField(
            model_name='report',
            name='rtype',
            field=models.CharField(max_length=1002),
        ),
    ]
