# Generated by Django 3.1.6 on 2021-03-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210326_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(max_length=201)),
                ('time', models.CharField(max_length=201)),
                ('action', models.CharField(max_length=201)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('sos_type', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
