# Generated by Django 3.1.6 on 2021-03-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210327_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='beat_id',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camera',
            name='division_id',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camera',
            name='range_id',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
