# Generated by Django 3.1.6 on 2021-04-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210328_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local_report',
            name='phone_no',
            field=models.CharField(max_length=200),
        ),
    ]
